# Generated by Django 3.1.2 on 2021-11-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('employee', 'project')},
        ),
    ]
