# Generated by Django 3.1.2 on 2021-12-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=10, unique=True)),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField(unique=True, verbose_name='Enter unique id')),
                ('e_name', models.CharField(max_length=100, verbose_name='Name')),
                ('e_dob', models.DateField()),
                ('e_email', models.EmailField(max_length=254, unique=True)),
                ('e_contact', models.IntegerField()),
                ('e_gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='female', max_length=6)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.department')),
                ('employees', models.ManyToManyField(through='employee.Assignment', to='employee.Employee')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(through='employee.Assignment', to='employee.Project'),
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('d_relation', models.CharField(choices=[('spouse', 'SPOUSE'), ('child', 'CHILD'), ('Father', 'FATHER'), ('Mother', 'MOTHER')], default='blank', max_length=6)),
                ('d_dob', models.DateField()),
                ('e_gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='female', max_length=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'dependent',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.project'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('employee', 'project')},
        ),
    ]
